# Copyright (c) 2021 Mert Bora Alper and EASE Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: S3 Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example:
    name: Example
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        example:
          - word-count
          - amplab1
          - amplab2
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-west-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/checkout@v2

      - name: Build driver
        working-directory: driver
        run: make

      - name: Build worker
        working-directory: examples/${{ matrix.example }}
        run: make

      - name: Start worker in the background
        working-directory: examples/${{ matrix.example }}
        env:
          PORT: 8080
        run: ./bin/${{ matrix.example }} &

      - name: Test
        working-directory: examples/${{ matrix.example }}
        run: |
          set -x

          ../../driver/bin/driver \
            -inputResourceBackend S3 \
            -interBack S3 -interHint s3://ease-lab-mare/workspaces/ci/${{ matrix.example }}/ \
            -outputBack S3 -outputHint s3://ease-lab-mare/workspaces/ci/${{ matrix.example }}/ \
            $(aws s3api list-objects --bucket ease-lab-mare --prefix examples/${{ matrix.example }}/inputs/ | jq -r '.Contents[].Key' | grep '.*.tsv' | sed 's/^/s3:\/\/ease-lab-mare\//') \
            > outputFileName

      - name: Verify
        working-directory: examples/${{ matrix.example }}
        run: aws s3 cp $(cat outputFileName) - | LC_ALL=C sort - | cmp expected-output.tsv -

      - name: Clean up S3
        if: ${{ always() }}
        run: aws s3 rm s3://ease-lab-mare/workspaces/ci/${{ matrix.example }}/ --recursive
